import type { Metadata } from "next";
import Link from "next/link";
import { LogoMark } from "@/app/logo";

export const metadata: Metadata = {
  title: "Security",
  description:
    "How Underwrite Copilot protects uploaded offering memoranda: private storage, database-level isolation, server-side keys, and no model training on your documents.",
  alternates: { canonical: "/security" },
};

// Every claim on this page is verifiable in the codebase or in a vendor's
// published terms. No aspirational statements, no certifications we don't
// hold. If a control isn't real yet, it doesn't appear here.
const SECTIONS: { h: string; body: string[] }[] = [
  {
    h: "The short version",
    body: [
      "Offering memorandums travel under confidentiality terms, so the bar is simple: your documents are visible to your account (and your team, if you create one) and to no one else. Isolation is enforced in the database itself, documents sit in private storage behind expiring links, analysis keys never reach the browser, and nothing you upload is used to train AI models.",
    ],
  },
  {
    h: "Where your OM lives",
    body: [
      "Uploaded PDFs are stored in a private storage bucket — there are no public URLs. When you view or download a document, the server issues a signed link that expires after one hour. Storage and database are hosted on Supabase, which encrypts data at rest; all traffic is encrypted in transit with TLS.",
    ],
  },
  {
    h: "Isolation between accounts",
    body: [
      "Every table that holds deal data is protected by Postgres row-level security. Queries run as your authenticated user, and the database — not just the application code — refuses to return rows that don't belong to your account or your team. A bug in a page can't leak another firm's pipeline, because the database itself won't serve it.",
    ],
  },
  {
    h: "AI analysis without training",
    body: [
      "The analysis is generated by Anthropic's Claude API. Under Anthropic's commercial API terms, inputs and outputs are not used to train models. We don't build datasets, benchmarks, or comps databases out of customer documents either — each analysis is produced for your account and stays there.",
    ],
  },
  {
    h: "Keys and payments",
    body: [
      "The Anthropic API key, database service credentials, and Stripe secrets exist only on the server — the code that touches them is marked server-only and cannot be bundled into the browser. Card details go directly to Stripe and never touch our servers; Stripe webhook events are signature-verified before they change anything.",
    ],
  },
  {
    h: "Deletion",
    body: [
      "Deleting a deal removes its documents and analyses. Deleting your account — self-serve, from the Account page — cancels any live subscription, removes your files from storage, and cascades through the database. No export ransom, no retention surprise beyond what law requires (for example, billing records).",
    ],
  },
  {
    h: "Who processes what",
    body: [
      "Supabase — database, authentication, and document storage. Anthropic — AI analysis of document contents via the Claude API. Stripe — payments and subscription state. Render — application hosting. Photon (OpenStreetMap) — address autocomplete; it receives only the address text you type into an address field, never your documents. Each vendor receives only what its job requires.",
    ],
  },
  {
    h: "What we don't claim",
    body: [
      "We don't hold a SOC 2 attestation today, and you won't find a badge here pretending otherwise. What you get instead is the architecture above, stated plainly. If you're evaluating us for a team and need something specific answered, email underwritecopilot.support@gmail.com and you'll get a straight answer.",
    ],
  },
];

export default function SecurityPage() {
  return (
    <div className="flex flex-1 flex-col">
      <header className="border-b border-line">
        <div className="mx-auto flex max-w-3xl items-center justify-between px-6 py-4">
          <Link href="/" className="flex items-center gap-2.5">
            <LogoMark className="h-8 w-8" />
            <span className="font-semibold tracking-tight">
              Underwrite Copilot
            </span>
          </Link>
          <Link
            href="/login?mode=signup"
            className="rounded-lg bg-brand px-3.5 py-1.5 text-sm font-medium text-white transition-colors hover:bg-brand-strong"
          >
            Get started
          </Link>
        </div>
      </header>

      <main className="mx-auto w-full max-w-3xl flex-1 px-6 py-12">
        <h1 className="text-3xl font-semibold tracking-tight">Security</h1>
        <p className="mt-2 text-sm text-muted">Last updated: July 7, 2026</p>
        <p className="mt-5 text-sm leading-relaxed text-muted">
          The question behind every upload: is it safe to put a confidential
          OM here? This page is the answer — how documents are stored, who can
          see them, and where they go. The{" "}
          <Link
            href="/privacy"
            className="font-medium text-brand hover:text-brand-strong"
          >
            privacy policy
          </Link>{" "}
          covers the full data-handling detail.
        </p>

        <div className="mt-10 space-y-8">
          {SECTIONS.map((s) => (
            <section key={s.h}>
              <h2 className="text-lg font-semibold tracking-tight">{s.h}</h2>
              {s.body.map((p, i) => (
                <p key={i} className="mt-2 text-sm leading-relaxed text-muted">
                  {p}
                </p>
              ))}
            </section>
          ))}
        </div>
      </main>

      <footer className="border-t border-line">
        <div className="mx-auto flex max-w-3xl flex-wrap items-center justify-between gap-3 px-6 py-6 text-xs text-muted">
          <span>Underwrite Copilot</span>
          <span className="flex gap-4">
            <Link href="/terms" className="transition-colors hover:text-ink">
              Terms
            </Link>
            <Link href="/privacy" className="transition-colors hover:text-ink">
              Privacy
            </Link>
            <Link href="/security" className="transition-colors hover:text-ink">
              Security
            </Link>
            <Link href="/" className="transition-colors hover:text-ink">
              Home
            </Link>
          </span>
        </div>
      </footer>
    </div>
  );
}
