import Link from "next/link";
import { LogoMark } from "@/app/logo";
import { ProcessorList } from "@/app/processor-list";
import { publicMetadata } from "@/lib/page-meta";

export const metadata = publicMetadata({
  title: "Security",
  description:
    "How Underwrite Copilot protects uploaded offering memoranda: private storage, database-level isolation, server-side keys, and no model training on your documents.",
  canonical: "/security",
});

// Every claim on this page is verifiable in the codebase or in a vendor's
// published terms. No aspirational statements, no certifications we don't
// hold. If a control isn't real yet, it doesn't appear here. The list of
// outside services is lib/data-processors, the privacy policy's list too,
// held to the hosts the code sends a user's data to.
const SECTIONS: { h: string; body: string[]; processors?: boolean }[] = [
  {
    h: "The short version",
    body: [
      "Offering memorandums travel under confidentiality terms, so the bar is simple: your documents are visible to your account (and your team, if you create one) and to no other person. To run your screen they are read by Anthropic's Claude API, and they are stored with Supabase — the list below names every outside service and what it receives. Isolation is enforced in the database itself (the reads that go round it are named below), documents sit in private storage behind expiring links, analysis keys never reach the browser, and nothing you upload is used to train AI models.",
    ],
  },
  {
    h: "Where your OM lives",
    body: [
      "Uploaded PDFs are stored in a private storage bucket — there are no public URLs. When you view or download a document, the server issues a signed link that expires after one hour. Storage and database are hosted on Supabase, which encrypts data at rest; all traffic is encrypted in transit with TLS.",
    ],
  },
  {
    h: "Isolation between accounts",
    body: [
      "Every table that holds deal data is protected by Postgres row-level security. While you are signed in, pages query as your authenticated user, and the database — not just the application code — refuses to return rows that don't belong to your account or your team, so a bug in one of those pages can't leak another firm's pipeline. Some reads and writes use the server's own key instead, behind the site's own checks rather than the database's: a shared link's page and its pictures; the pictures in our emails and their one-click unsubscribe; the background work that runs your screens and the analyses beside them; the questions you ask about a deal; every stored file — your memorandum, your documents and the deal's pictures — read through one gate that holds each file to the deal or account it belongs to; the buy box and branding a memo, report or export reads; your account's settings and billing; deleting your account, which removes its files and sign-in and hands what you added to a team's pipeline to that team's owner; and the public market figures every visitor sees.",
    ],
  },
  {
    h: "AI analysis without training",
    body: [
      "The analysis is generated by Anthropic's Claude API. Under Anthropic's Commercial Terms of Service, Anthropic “may not train models on Customer Content” — what we send it and what it sends back — and that content is treated as our confidential information. We don't build datasets, benchmarks, or comps databases out of customer documents either — each analysis is produced for your account and stays there.",
    ],
  },
  {
    h: "Keys and payments",
    body: [
      "The Anthropic API key, database service credentials, and Stripe secrets exist only on the server — the code that touches them is marked server-only and cannot be bundled into the browser. Card details go directly to Stripe and never touch our servers; Stripe webhook events are signature-verified before they change anything.",
    ],
  },
  {
    h: "Deletion",
    body: [
      "Deleting a deal removes its documents and analyses. Deleting your account — self-serve, from the Account page — cancels any live subscription, removes your files from storage, and cascades through the database. No export ransom, no retention surprise beyond what law requires (for example, billing records).",
    ],
  },
  {
    h: "Who processes what",
    body: [
      "Each outside service receives only what its job requires. The documents themselves are stored with Supabase and read by Anthropic, on an app Render hosts; every other service receives only what is named beside it.",
    ],
    processors: true,
  },
  {
    h: "What we don't claim",
    body: [
      "We don't hold a SOC 2 attestation today, and you won't find a badge here pretending otherwise. What you get instead is the architecture above, stated plainly. If you're evaluating us for a team and need something specific answered, email underwritecopilot.support@gmail.com and you'll get a straight answer.",
    ],
  },
];

export default function SecurityPage() {
  return (
    <div className="flex flex-1 flex-col">
      <header className="border-b border-line">
        <div className="mx-auto flex max-w-3xl items-center justify-between px-6 py-4">
          <Link href="/" className="flex items-center gap-2.5">
            <LogoMark className="h-8 w-8" />
            <span className="font-semibold tracking-tight">
              Underwrite Copilot
            </span>
          </Link>
          <Link
            href="/login?mode=signup"
            className="rounded-lg bg-brand px-3.5 py-1.5 text-sm font-medium text-white transition-colors hover:bg-brand-strong"
          >
            Get started
          </Link>
        </div>
      </header>

      <main id="main" className="mx-auto w-full max-w-3xl flex-1 px-6 py-12">
        <h1 className="text-3xl font-semibold tracking-tight">Security</h1>
        <p className="mt-2 text-sm text-muted">Last updated: October 5, 2026</p>
        <p className="mt-5 text-sm leading-relaxed text-muted">
          Every upload comes down to one thing: whether it is safe to put a
          confidential OM here. This page is the answer — how documents are
          stored, who can see them, and where they go. The{" "}
          <Link
            href="/privacy"
            className="font-medium text-brand hover:text-brand-strong"
          >
            privacy policy
          </Link>{" "}
          covers the full data-handling detail.
        </p>

        <div className="mt-10 space-y-8">
          {SECTIONS.map((s) => (
            <section key={s.h}>
              <h2 className="text-lg font-semibold tracking-tight">{s.h}</h2>
              {s.body.map((p, i) => (
                <p key={i} className="mt-2 text-sm leading-relaxed text-muted">
                  {p}
                </p>
              ))}
              {s.processors && <ProcessorList />}
            </section>
          ))}
        </div>
      </main>

      <footer className="border-t border-line">
        <div className="mx-auto flex max-w-3xl flex-wrap items-center justify-between gap-3 px-6 py-6 text-xs text-muted">
          <span>Underwrite Copilot</span>
          <span className="flex gap-4">
            <Link href="/why" className="transition-colors hover:text-ink">
              Why
            </Link>
            <Link href="/terms" className="transition-colors hover:text-ink">
              Terms
            </Link>
            <Link href="/privacy" className="transition-colors hover:text-ink">
              Privacy
            </Link>
            <Link href="/security" className="transition-colors hover:text-ink">
              Security
            </Link>
            <Link href="/whats-new" className="transition-colors hover:text-ink">
              What&apos;s new
            </Link>
            <Link href="/" className="transition-colors hover:text-ink">
              Home
            </Link>
          </span>
        </div>
      </footer>
    </div>
  );
}
